@echo off
echo Loading Script
set /a num=%random% %%10
timeout /t %num% /nobreak >nul
echo Script Ready!
:start
color 2
echo %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  	%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  						%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%    %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% 
echo				%random% 	%random% 							%random% 		%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% 			%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  					%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% 			%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% 	 %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%
echo 				%random% %random% 		%random% 	%random% 							%random%       %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%       %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%      %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%        %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%          %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%   	%random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random%
echo			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%   %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%     %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random%
echo %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 						%random% %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random% %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 			%random% 	%random% 				%random% 	%random% 					%random% 	%random% 							%random% 	%random% 							%random%  %random% 	%random% 	%random% 		%random% 	%random% 
goto start